#
# Deployment of a RabbitMQ server.
#
#
# Deployment of a RabbitMQ server.
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ template "fullname" . }}"
  labels:
    app: "{{ template "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      annotations:
        productID: RabbitMQ_373_free_00000
        productName: RabbitMQ
        productVersion: 3.7.3
      labels:
        app: {{ template "fullname" . }}
    spec:
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.rabbit.image.repository }}:{{ .Values.rabbit.image.tag }}"
        imagePullPolicy: {{ .Values.rabbit.image.pullPolicy | quote }}
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: K8S_SERVICE_NAME
          value: {{ template "fullname" . }}
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbit.rabbitmqUsername | quote }}
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: rabbitmq-password
        - name: RABBITMQ_ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: rabbitmq-erlang-cookie
        {{ if .Values.rabbit.tls.enabled -}}
        - name: RABBITMQ_CTL_ERL_ARGS
          value: "-proto_dist inet_tls"
        {{ end -}}
        - name: RABBITMQ_NODE_TYPE
          value: {{ .Values.rabbit.rabbitmqNodeType | quote }}
        - name: RABBITMQ_NODENAME
          value: {{ printf "%s@%s" .Values.rabbit.rabbitmqNodeName "localhost" | quote }}
        - name: RABBITMQ_CLUSTER_NODE_NAME
          value: {{ .Values.rabbit.rabbitmqClusterNodeName | quote }}
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ .Values.rabbit.rabbitmqVhost | quote }}
        {{ if .Values.rabbit.tls.enabled -}}  
        - name: RABBITMQ_SSL_CERT_FILE
          value: "/opt/rabbitmq/tls/cert.pem"
        - name: RABBITMQ_SSL_KEY_FILE
          value: "/opt/rabbitmq/tls/key.pem"
        - name: RABBITMQ_SSL_CA_FILE
          value: "/opt/rabbitmq/tls/cacert.pem"         
        {{ end -}}
        ports:
        - name: epmd
          containerPort: 4369
        {{ if .Values.rabbit.tls.enabled -}}  
        - name: ampq
          containerPort: 5671
        - name: dist
          containerPort: 25671
        - name: stats
          containerPort: 15671
        {{ else }}
        - name: ampq
          containerPort: 5672
        - name: dist
          containerPort: 25672
        - name: stats
          containerPort: 15672
        {{ end }}
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /var/lib/rabbitmq
        {{ if .Values.rabbit.tls.enabled -}}  
        - name: tls
          mountPath: /opt/rabbitmq/tls   
        {{ end -}}         
        resources:
{{ toYaml .Values.rabbit.resources | indent 10 }}
      volumes:
      {{ if .Values.rabbit.tls.enabled -}}  
      - name: tls
        secret:
          secretName: {{ template "fullname" . }}
          defaultMode: 0644
          items:
          - key: tls.crt
            path: cert.pem
          - key: tls.key
            path: key.pem
  
          - key: tls.cacrt
            path: cacert.pem              
      {{ end -}}
      - name: data
      {{- if .Values.rabbit.persistence.enabled }}
        persistentVolumeClaim:
          {{- if .Values.rabbit.dataPVC.existingClaimName }}
          claimName: {{ .Values.rabbit.dataPVC.existingClaimName }}
          {{- else }}
          claimName: {{ .Release.Name }}-{{ .Values.dataPVC.name }}
          {{- end -}}
      {{- else }}
        emptyDir: {}
      {{- end -}}