apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-server
  labels:
    app: {{ template "fullname" . }}-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: ampq
    port: {{ .Values.rabbitmqNodePort }}
    targetPort: ampq
  - name: dist
    port: {{ .Values.rabbitmqNodePort | add 20000 }}
    targetPort: dist
  - name: stats
    port: {{ .Values.rabbitmqManagerPort }}
    targetPort: stats
  selector:
    app: {{ template "fullname" . }}